# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

resources:
  repositories:
  - repository: githubRepo
    type: github
    name: marekzmyslowski/testrepo
    endpoint: MyGitHubServiceConnection  # Name of the GitHub service connection

pool: Default


steps:
- checkout: githubRepo
- script: echo "Checked out code from GitHub using service connection"
